config/routes.rb
Rails.application.routes.draw do
  match '/help',    to: 'static_pages#help',    via: 'get'
  root  'static_pages#home'
  match '/:tag',  :to => 'boards#show', :as => :tag,    via: 'get'
  match '/:tag/:post', to: 'topics#show',  via: 'get'
  resources :topics, only: :create

end

app/models/board.rb
class Board < ActiveRecord::Base
	has_many :topics, dependent: :destroy
	validates :long_name, length: { maximum: 30 }
	VALID_EMAIL_REGEX = /\A[A-z]{1,4}\z/
  	validates :tag, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic, inverse_of: :posts
	#validates :topic, presence: true 
	#validates :topic_id, presence: true 
	default_scope -> { order('updated_at ASC') }
	validates :content, presence: true, length: { maximum: 1600 }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :posts, inverse_of: :topic
	accepts_nested_attributes_for :posts
	validates :posts, presence: true
	
	belongs_to :board
	validates :board, presence: true 
	default_scope -> { order('updated_at DESC') }
	validates :board_id, presence: true
	validates :caption, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_board_list

  private

  def get_board_list
    @board_list=Board.all
  end  

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def show
  	@board=Board.find_by_tag(params[:tag])
  	if !@board
  		redirect_to root_path
  	else
  		@topics=@board.topics.paginate(page: params[:page], per_page: 10)
  		@new_topic = @board.topics.build
  		@new_topic.posts.new
  	end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def help
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      flash[:success] = "Thread successfuly created!"
    else
      @topic.errors.full_messages.each do |error_msg| 
        flash[:error] = error_msg
      end
    end
    redirect_to '/'+Board.find(@topic.board_id).tag
  end


  def show
    board=Board.find_by(tag: params[:tag])
    post = Post.find_by(id: params[:post])
    if(board && post && post.topic.board==board)
      @full=true
      @topic=post.topic
    else
      flash[:error] = "Thread not found"
      redirect_to '/' + if board then board.tag else "" end
    end
  end


	private

	    def topic_params
        posts_attributes = {
          posts_attributes: [:content]
        }
	      params.require(:topic).permit(:caption, :board_id, posts_attributes)
	    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "SimpleCh"
    if page_title.empty?
      base_title
    else
      "#{page_title}"
    end
  end

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
    
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/boards/_board_header.html.erb
<h1 class="pan10">/<%= @board.tag %>/ - <%= @board.long_name %></h1>

app/views/boards/_new_topic_form.html.erb
<h4 class="form_show_link"  onclick="showTopicForm()" style="text-align: center; text-decoration: underline; cursor: pointer;">
  New Thread
</h4>
<div id="new_topic_bar">
  <%= form_for(@new_topic) do |f| %>
    <div class="row">
    	<div style="padding-top: 3px;" class="span1">
    		<b>Caption</b>
    	</div>
      <%= f.text_field :caption, placeholder: "Thread caption..", class:"span7" %>
      <%= f.submit "Post", class: "btn span2 pull-right" %>
    </div>
    <div class="field">
      <%= f.hidden_field :board_id, :value => @board.id  %>
    </div>
    <%= f.fields_for :posts do |ff| %>
      <div class="row">
        <div style="padding-top: 3px;" class="span1">
          <b>Post</b>
        </div>
        <%= ff.text_area :content, placeholder: "Origial post..", rows: 7, style:"resize: none;", class:"span7" %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="row">
</div>

app/views/boards/show.html.erb
<% provide(:title, @board.long_name + " - SimpleCh") %>
<%= render 'board_header' %>
	<%= render 'new_topic_form' %>

<div>
    <ol class="threads">
      <%= render @topics %>
    </ol>
    <div class="thread-pagination"><%= will_paginate @topics %></div>
</div>




app/views/layouts/_header.html.erb


<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <h3><%= link_to "SimpleCh", root_path, id: "logo" %> </h3>
      <nav>
        <ul class="nav pull-right", id:"board-list-short">
          <li><h4>Boards: </h4></li>
          <%  @board_list.each do |el| %>
            <li><%= link_to "/ "+el.tag+" /", tag_path(el.tag) , title: el.long_name, rel: 'tooltip'%></li>
          <% end %>  
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))  %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/header' %>
<div class="lame_spacer"/>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<body>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posts/_post.html.erb
<% if post==post.topic.posts.first %>
	<li class="post_frame_first">
	<span class="post_caption">
		<%= post.topic.caption %>
	</span>	
<% else %>
	<li class="post_frame">
<% end %>
		<span class="post_timestamp">
			Posted <%= time_ago_in_words(post.created_at) %> ago.
		</span>	
		<span class="post_number">
			<%= link_to "№"+post.id.to_s, "/"+post.topic.board.tag+"/"+post.id.to_s %>
		</span>
		</br>
		<span class="post_value"><%= post.content %></span>
	</li>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<h1>Welcome</h1>
<h3>To the neat and simple imageboard world</h3>
</div>

app/views/topics/_topic.html.erb
<% if @full %>
	<% @posts=@topic.posts.all[1..-1] %>
	<% @board=topic.board %>
	<%= render 'boards/board_header' %>
<% end %>
<%= render topic.posts.first %>

<% if @full %>
	<% @posts=@topic.posts.all[1..-1] %>
<% end %>

<% if @posts %>
	<%= render @posts %>
<% end %>

app/views/topics/show.html.erb
<%= render @topic %>